JAVAC = javac
JAVA = java
SRC = HousePainter.java
OUT = HousePainter.class

$(OUT): $(SRC)
	$(JAVAC) $(SRC)

run1: $(OUT)
	$(JAVA) HousePainter 1

run2: $(OUT)
	$(JAVA) HousePainter 2

run3: $(OUT)
	$(JAVA) HousePainter 3

run4: $(OUT)
	$(JAVA) HousePainter 4

clean:
	del *.class